### ISSUE TITLE
Feature request - Domain allowlist

### ISSUE THREAD

**Issue by mohdnr** [cds-snc/url-shortener#2]
Good opportunity to re-use notifys allowlist to ensure URL's only point to government resources.

[Code example](https://github.com/cds-snc/notification-admin/blob/3ba48d2aca66292d407c1cc08dd86cb9073cc557/app/utils.py#L59)
[List of domains](https://github.com/cds-snc/notification-admin/blob/master/app/email_domains.txt)

**Comment by feralbob** [comment]
Thinking about this - what is the purpose of the allowlist?  
I guess it depends on the deployed context of a URL shortener

If deployed for a specific service it may make sense for that service to limit the short urls that are generated. But if we consider notify, it supports many more downstream services. 

In the context of a general GC shortener on a top GC domain e.g. l.gc.ca - then the use case may not support allowlisting. e.g. If a GC department wanted to use short links in it's social media then in theory they could link anywhere not only to fellow gc domains. (e.g. GAC may want to link to a German URL for the Trade Commissioners service)

So broadly speaking I think allowlists/denylists need to specified per user/API and at this stage we haven't done any authentication/authorization/api - because that will significantly increase complexity. e.g. Are users individuals, groups, services, departments? I do think that this is inevitable - and then allow/deny listing needs to be within the organizational context of a service/department/group.

Thoughts and comments from others welcome.

**Comment by mohamed-cds** [comment]
Primarily to reduce the risk of this service being used to bypass URL based security mechanisms . Detectify has a good blog post about it [here](https://blog.detectify.com/2019/05/16/the-real-impact-of-an-open-redirect/).

Although if this service requires authentication and is only open to government employees, then the risk is reduced enough for this to not be a priority feature.

**Comment by sylviamclaughlin** [comment]
We have added this feature already but might need revisiting to make sure that all domains are included.

**Comment by maxneuvians** [comment]
We are managing this through an ENV variable right now so this should be easy enough to adjust over time
